### ISSUE TITLE
Error if folder doesn't exist

### ISSUE THREAD

**Issue by HarpoMarx69** [francescolorenzetti/types-4-strapi#1]
First: thanks a lot for this, Francesco!!!

When I started the script the first time it threw an error:

```
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'types/IUser.ts'
←[90m    at Object.openSync (fs.js:497:3)←[39m
←[90m    at Object.writeFileSync (fs.js:1528:35)←[39m
    at Object.<anonymous> (types-4-strapi.js:18:4)
```

After manually creating the missing directory everything worked fine. Perhaps a check and creation of missing necessary directory could prevent this.

Best regards
Klaus

**Comment by francescolorenzetti** [comment]
Thank you @HarpoMarx69, fixed it.

**Comment by HarpoMarx69** [comment]
That was VERY quick. 
Thanks a lot!
