### ISSUE TITLE
Wrong types for components

### ISSUE THREAD

**Issue by haegemonia76** [francescolorenzetti/types-4-strapi#14]
The title says everything, but for more explication :
this is the generated types for one of my dynamiczones

```ts
export interface CallToAction {
  id: number;
  attributes: {
    text: string;
    link: string;
  }
}
```
but my response looks like :
```js
{
  // ...
  "dynamic": [
    {
      "id": 1,
      "__component": "content.call-to-action",
      "text": "test",
      "link": "https://google.com"
    },
    // ...
  ]
  // ...
}
```

It seems like the **attributes** property does not exists on components at all

**Comment by francescolorenzetti** [comment]
I rolled back your implementation of the dynamiczone, temporarily using `any` again. There were too many issues. I'll re-write it when I have some time.

**Comment by francescolorenzetti** [comment]
Fixed in latest version
