### ISSUE TITLE
generate types for `Components`

### ISSUE THREAD

**Issue by yulafezmesi** [francescolorenzetti/types-4-strapi#3]
Great utility! I would like to contribute, thank you!

Here is the first missing part that I've noticed while testing. Currently, we can not generate interfaces for component content types. So I think we need to add support for this. Any thoughts about that?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/45617686/156900441-5e4d1908-e278-47f7-9357-7af8eb958e45.png">

**Comment by francescolorenzetti** [comment]
Thank you for flagging this, I'll push a quick fix (components' type will be `any`), the spend some time later to code a proper solution.

Since components and types use a very similar schema, it should be easy to reuse existing logic.

**Comment by francescolorenzetti** [comment]
Pushed the `any` fix, now working on a full solution in the [components](https://github.com/francescolorenzetti/types-4-strapi/tree/components) branch.
