### ISSUE TITLE
Other types support and optional property

### ISSUE THREAD

**Issue by fadhilx** [francescolorenzetti/types-4-strapi#7]
First of all,thanks for this library. I have 2 question/request
1. there's serveral types that did not considered as valid type and will return compiler error:
`text`
`biginteger`
`date`
`datetime`
`time`
`dynamiczone`

![image](https://user-images.githubusercontent.com/15516786/161479246-0ec83729-f22d-453e-bd6c-f43b4b77f3f6.png)

2. have you consider using require to make the property optional. for example if the schema is like this; 
```json
{ "attributes":{
    "name": {
      "type": "string",
      "required": true
     },
    "photo": {
      "type": "media",
      "required": false       // <----------- not require
     }
    }
}
```
then the out put should be
```typescript
export interface CustomObject{
  id: number;
  attributes: {
    name: string;   // <--- the `name` property is required in the schema
    photo?: { data: Media };  //<----------- not require
  }
}
```

**Comment by francescolorenzetti** [comment]
All this is done, aside from support from dynamiczone. Please update to v 1.0.10
